apiVersion: v1 
kind: Service
metadata: 
  name: deployment-np-service
  labels:
    app: deployment-np-service

spec:
  type: NodePort
  selector:
    app: first-deployment
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31224 # NodePort (Optional)(Node Port Range: 30000-32768)
