apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: first-pod

spec:
  containers:
    - name: first-pod
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80    

