apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold  
provisioner: pd.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-balanced
  fstype: ext4
  replication-type: none