apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-myapp1
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: myapp1-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
 
#For CIP Service
#kubectl run -i --tty load-generator --rm --image=busybox --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://myapp1-cip-service; done"

#For LB Service
#kubectl run -i --tty load-generator --rm --image=busybox --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://myapp1-lb-service; done"

# kubectl get hpa
# kubectl get hpa -w or --watch
# kubectl top pods or name of pods
# kubectl top nodes



