apiVersion: v1 or apps/v1
kind: Pod,ReplicaSet,Deployment 
metadata:
  name: 
  labels:
    app: 

spec:  # For Pods
  containers:
    - name: 
      image: 
      ports:
        - containerPort:

spec:  # For ReplicaSet
  replicas: 
  selector:
    matchLabels:
      app: 
      
  template:
    metadata:
      name: 
      labels:
        app: 
    spec:
      containers:
        - name: 
          image: 
          ports:
            - containerPort:           


spec:          # for service for NodePort
  type: NodePort
  selector:
    app:
  ports:
    - name: http
      port: 80 # Service Port
      targetPort: # Container Port
      nodePort: 31222


spec:            # for service for LoadBalancer
  type: LoadBalancer
  selector:
    app:
  ports:
    - name: http
      port: 80             # Service Port
      targetPort: 80       # Container Port
      


