apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: pod-replicaset
  labels:
    app:  pod-replicaset 

spec:  
  replicas: 3
  selector:
    matchLabels:
      app: pod-replicaset
      
  template:
    metadata:
      name: pod-replicaset
      labels:
        app: pod-replicaset
    spec:
      containers:
        - name: pod-replicaset
          image: stacksimplify/kubenginx:2.0.0
          ports:
            - containerPort: 80    



