apiVersion: v1 
kind: Service
metadata: 
  name: pod-np-service
  labels:
    app: pod-np-service

spec:
  type: NodePort
  selector:
    app: pod-replicaset
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31223 # NodePort (Optional)(Node Port Range: 30000-32768)
